version: '3'

services:
  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/db


volumes:
  db:
